build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.16"
  i386: "ghcr.io/home-assistant/i386-base:3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: KNXD daemon"
  org.opencontainers.image.description: "Home Assistant Add-on: KNXD daemon"
  org.opencontainers.image.source: "https://github.com/da-anda/hass-io-addons/tree/master/knxd"
args:
  KNXD_VERSION: 0.14.56
  KNXD_REPO: https://github.com/knxd/knxd.git
